// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgohguruooqhqappurbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnb2hndXJ1b29xaHFhcHB1cmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwMjc2MDMsImV4cCI6MjA5NjYwMzYwM30.5jPO6PQ1f_Ep2X2dbJYFa_rb1OYZELbjdIWJ9o9CBl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});